### ISSUE TITLE
AMD ROCm, OOM error

### ISSUE THREAD

**Issue by markg85** [xlite-dev/flux-faster#3]
Hi,

The dreaded error in image generation and AMD. Out Of Memory (OOM). My GPU is a 7900XT (20GB).

~~~
PYTORCH_HIP_ALLOC_CONF=expandable_segments:True python gen_image.py --prompt "A cat playing with a ball of yarn" --output-file output.png --compile_export_mode compile
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 19.58it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 69.95it/s]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers                                    | 0/2 [00:00<?, ?it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  9.03it/s]
/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py:1329: UserWarning: expandable_segments not supported on this platform (Triggered internally at /var/lib/jenkins/pytorch/c10/hip/HIPAllocatorConfig.h:29.)
  return t.to(
Traceback (most recent call last):
  File "/dockerx/flux-faster/gen_image.py", line 29, in <module>
    main(args)
  File "/dockerx/flux-faster/gen_image.py", line 14, in main
    pipeline = load_pipeline(args)
               ^^^^^^^^^^^^^^^^^^^
  File "/dockerx/flux-faster/utils/pipeline_utils.py", line 562, in load_pipeline
    ).to(args.device)
      ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 541, in to
    module.to(device, dtype)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/diffusers/models/modeling_utils.py", line 1383, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 72.00 MiB. GPU 0 has a total capacity of 19.98 GiB of which 150.00 MiB is free. Of the allocated memory 19.65 GiB is allocated by PyTorch, and 8.40 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
~~~

I don't see it in this crash report but i do know what "usually" causes this. It's the VAE and AMDs default of interpreting that at, i believe, bf16 which triggers a bug/feature of sucking up all available memory. In for example ComfyUI i have this same issue and there i just need to set `--fp16-vae` to make it work. 

Any idea how i can do this same trick in this code? I'm just assuming the VAE is the cause here too.

As an aside but i'm really keen on knowing this:
```
def download_hosted_file(filename, output_path):
    # Download hosted binaries from huggingface Hub.
    from huggingface_hub import hf_hub_download

    REPO_NAME = "jbschlosser/flux-fast"
    hf_hub_download(REPO_NAME, filename, local_dir=os.path.dirname(output_path))
```

How the heck do you download those models? The script is downloading a lot and i "think" it does so from `jbschlosser/flux-fast` but that repo doesn't even exist on huggingface. How does this magic work?

**Comment by markg85** [comment]
Hmm, the model size might have been the issue here, not VEA.
Could you recommend a model repository that works with 20GB of VRAM and this project? All your current options require more.

**Comment by DefTruth** [comment]
@markg85 please try the example in cache-dit: https://github.com/vipshop/cache-dit/blob/main/examples/pipeline/run_hunyuan_image_2.1.py and https://github.com/vipshop/cache-dit/blob/main/examples/pipeline/run_flux.py, you can add the int4_w4a16_wo workflow to run_flux.py

```python
# CPU -> GPU VRAM < 24GiB ? -> Int4 weight only on CPU -> GPU
```

**Comment by markg85** [comment]
> [@markg85](https://github.com/markg85) please try the example in cache-dit: https://github.com/vipshop/cache-dit/blob/main/examples/pipeline/run_hunyuan_image_2.1.py and https://github.com/vipshop/cache-dit/blob/main/examples/pipeline/run_flux.py, you can add the int4_w4a16_wo workflow to run_flux.py
> 
> # CPU -> GPU VRAM < 24GiB ? -> Int4 weight only on CPU -> GPU

Thank you for the thoughtful reply and willingness to help, that's much appreciated!

Unfortunately though, none of these options would help (if they would even work). I want (or wanted) to use this in my workflow to speed things up. Individual scripts aren't going to make this any easier. Regardless though, i said "wanted" for a reason. I gave up on AMD because it just is one fuc**** garbage platform when it comes it image generation. Turns out that going the nvidia route is very cheap. Now when i want to do something with image generation i just rent an nvidia GPU (4090, 5090) for between 0.20 and 0.50 cents/hour. That beats going to the trouble of getting it to work on AMD.
